### ISSUE TITLE
Install instructions point to wrong git repo and missing albumentations requirement.

### ISSUE THREAD

**Issue by a1270** [isamu-isozaki/fewshot-textual-inversion-low-memory#1]
It points to `https://github.com/afiaka87/glide-finetune.git` instead of `https://github.com/isamu-isozaki/fewshot-textual-inversion-low-memory.git`.

In order to solve the albumentations requirement i just did a `pip install --upgrade albumentations` and so good so far.

**Comment by isamu-isozaki** [comment]
@a1270 Thanks for the issue! Should be fixed now
